### ISSUE TITLE
Hung upload process

### ISSUE THREAD

**Issue by rysi3k** [gphotosuploader/gphotos-uploader-cli#167]
**Describe the bug**
When I tried to upload photos using 1.0.1 version upload process hangs after few files and never start again. Restart process fixes it for another few files.
Not matter how many workers I have. After hung I waited whole night without any change.
I tried even add some extra log lines to find problem but no idea what happened. I prefer JS over GO ;)

Thanks for any clue what could be wrong. 

My config:
```
{
  SecretsBackendType: file,
  APIAppCredentials: {
    ClientID:     "922....",
    ClientSecret: "TGLls....",
  }
  jobs: [
    {
      account: ....
      sourceFolder: /Volumes/data/photo
      makeAlbums: {
        enabled: true
        use: folderPath
      }
      uploadVideos: true
      includePatterns: [ "20??/**/**" ]
      excludePatterns: [ "!DRUK", "!M", ".DS_Store" ]
    }
  ]
}
```

Example output of hung process:
```
[info]   75812 files pending to be uploaded in folder '/Volumes/data/photo'.
[debug]  Worker #3 processing: /Volumes/data/photo/2008/2008 05 02/100_0001.JPG
[warn]   Start file=/Volumes/data/photo/2008/2008 05 02/100_0001.JPG
[debug]  Worker #1 processing: /Volumes/data/photo/2008/2008 04 27/100_0574.jpg
[warn]   Start file=/Volumes/data/photo/2008/2008 04 27/100_0574.jpg
[debug]  Worker #4 processing: /Volumes/data/photo/2008/2008 05 02/100_0002.JPG
[warn]   Start file=/Volumes/data/photo/2008/2008 05 02/100_0002.JPG
[debug]  Worker #2 processing: /Volumes/data/photo/2008/2008 05 02/100_0001.MOV
[warn]   Start file=/Volumes/data/photo/2008/2008 05 02/100_0001.MOV
[debug]  Worker #5 processing: /Volumes/data/photo/2008/2008 05 02/100_0003.JPG
[warn]   Start file=/Volumes/data/photo/2008/2008 05 02/100_0003.JPG
[warn]   Error? file=/Volumes/data/photo/2008/2008 05 02/100_0001.JPG, error=<nil>
[warn]   Tracking file=/Volumes/data/photo/2008/2008 05 02/100_0001.JPG
[warn]   Tracking done file=/Volumes/data/photo/2008/2008 05 02/100_0001.JPG, error=<nil>
[debug]  Worker job done {/Volumes/data/photo/2008/2008 05 02/100_0001.JPG processed successfully <nil>}
[debug]  Worker #3 processing: /Volumes/data/photo/2008/2008 05 02/100_0004.JPG
[warn]   Start file=/Volumes/data/photo/2008/2008 05 02/100_0004.JPG
[warn]   Error? file=/Volumes/data/photo/2008/2008 04 27/100_0574.jpg, error=<nil>
[warn]   Tracking file=/Volumes/data/photo/2008/2008 04 27/100_0574.jpg
[warn]   Tracking done file=/Volumes/data/photo/2008/2008 04 27/100_0574.jpg, error=<nil>
[debug]  Worker job done {/Volumes/data/photo/2008/2008 04 27/100_0574.jpg processed successfully <nil>}
[debug]  Worker #1 processing: /Volumes/data/photo/2008/2008 05 02/100_0005.JPG
[warn]   Start file=/Volumes/data/photo/2008/2008 05 02/100_0005.JPG
[warn]   Error? file=/Volumes/data/photo/2008/2008 05 02/100_0002.JPG, error=<nil>
[warn]   Tracking file=/Volumes/data/photo/2008/2008 05 02/100_0002.JPG
[warn]   Tracking done file=/Volumes/data/photo/2008/2008 05 02/100_0002.JPG, error=<nil>
[debug]  Worker job done {/Volumes/data/photo/2008/2008 05 02/100_0002.JPG processed successfully <nil>}
[debug]  Worker #4 processing: /Volumes/data/photo/2008/2008 05 02/100_0006.JPG
[warn]   Start file=/Volumes/data/photo/2008/2008 05 02/100_0006.JPG
[warn]   Error? file=/Volumes/data/photo/2008/2008 05 02/100_0001.MOV, error=<nil>
[warn]   Tracking file=/Volumes/data/photo/2008/2008 05 02/100_0001.MOV
[warn]   Tracking done file=/Volumes/data/photo/2008/2008 05 02/100_0001.MOV, error=<nil>
[debug]  Worker job done {/Volumes/data/photo/2008/2008 05 02/100_0001.MOV processed successfully <nil>}
[debug]  Worker #2 processing: /Volumes/data/photo/2008/2008 05 02/100_0007.JPG
[warn]   Start file=/Volumes/data/photo/2008/2008 05 02/100_0007.JPG
[warn]   Error? file=/Volumes/data/photo/2008/2008 05 02/100_0003.JPG, error=<nil>
[warn]   Tracking file=/Volumes/data/photo/2008/2008 05 02/100_0003.JPG
[warn]   Tracking done file=/Volumes/data/photo/2008/2008 05 02/100_0003.JPG, error=<nil>
[debug]  Worker job done {/Volumes/data/photo/2008/2008 05 02/100_0003.JPG processed successfully <nil>}

... skipped some log lines...

[debug]  Worker #1 processing: /Volumes/data/photo/2008/2008 05 02/DSCN0079.JPG
[warn]   Start file=/Volumes/data/photo/2008/2008 05 02/DSCN0079.JPG
[warn]   Error? file=/Volumes/data/photo/2008/2008 05 02/DSCN0074.JPG, error=<nil>
[warn]   Tracking file=/Volumes/data/photo/2008/2008 05 02/DSCN0074.JPG
[warn]   Tracking done file=/Volumes/data/photo/2008/2008 05 02/DSCN0074.JPG, error=<nil>
[debug]  Worker job done {/Volumes/data/photo/2008/2008 05 02/DSCN0074.JPG processed successfully <nil>}
[debug]  Worker #4 processing: /Volumes/data/photo/2008/2008 05 02/DSCN0080.JPG
[warn]   Start file=/Volumes/data/photo/2008/2008 05 02/DSCN0080.JPG
[warn]   Error? file=/Volumes/data/photo/2008/2008 05 02/DSCN0075.JPG, error=<nil>
[warn]   Tracking file=/Volumes/data/photo/2008/2008 05 02/DSCN0075.JPG
[warn]   Tracking done file=/Volumes/data/photo/2008/2008 05 02/DSCN0075.JPG, error=<nil>
[debug]  Worker job done {/Volumes/data/photo/2008/2008 05 02/DSCN0075.JPG processed successfully <nil>}
[debug]  Worker #2 processing: /Volumes/data/photo/2008/2008 05 02/DSCN0081.JPG
[warn]   Start file=/Volumes/data/photo/2008/2008 05 02/DSCN0081.JPG
[warn]   Error? file=/Volumes/data/photo/2008/2008 05 02/DSCN0076.JPG, error=<nil>
[warn]   Tracking file=/Volumes/data/photo/2008/2008 05 02/DSCN0076.JPG
[warn]   Tracking done file=/Volumes/data/photo/2008/2008 05 02/DSCN0076.JPG, error=<nil>
[debug]  Worker job done {/Volumes/data/photo/2008/2008 05 02/DSCN0076.JPG processed successfully <nil>}
[debug]  Worker #5 processing: /Volumes/data/photo/2008/2008 05 02/DSCN0082.JPG
[warn]   Start file=/Volumes/data/photo/2008/2008 05 02/DSCN0082.JPG
[warn]   Error? file=/Volumes/data/photo/2008/2008 05 02/DSCN0077.JPG, error=<nil>
[warn]   Tracking file=/Volumes/data/photo/2008/2008 05 02/DSCN0077.JPG
[warn]   Tracking done file=/Volumes/data/photo/2008/2008 05 02/DSCN0077.JPG, error=<nil>
[debug]  Worker job done {/Volumes/data/photo/2008/2008 05 02/DSCN0077.JPG processed successfully <nil>}
[warn]   Error? file=/Volumes/data/photo/2008/2008 05 02/DSCN0079.JPG, error=<nil>
[warn]   Tracking file=/Volumes/data/photo/2008/2008 05 02/DSCN0079.JPG
[warn]   Tracking done file=/Volumes/data/photo/2008/2008 05 02/DSCN0079.JPG, error=<nil>
[debug]  Worker job done {/Volumes/data/photo/2008/2008 05 02/DSCN0079.JPG processed successfully <nil>}
[warn]   Error? file=/Volumes/data/photo/2008/2008 05 02/DSCN0080.JPG, error=<nil>
[warn]   Tracking file=/Volumes/data/photo/2008/2008 05 02/DSCN0080.JPG
[warn]   Tracking done file=/Volumes/data/photo/2008/2008 05 02/DSCN0080.JPG, error=<nil>
[debug]  Worker job done {/Volumes/data/photo/2008/2008 05 02/DSCN0080.JPG processed successfully <nil>}
[warn]   Error? file=/Volumes/data/photo/2008/2008 05 02/DSCN0081.JPG, error=<nil>
[warn]   Tracking file=/Volumes/data/photo/2008/2008 05 02/DSCN0081.JPG
[warn]   Tracking done file=/Volumes/data/photo/2008/2008 05 02/DSCN0081.JPG, error=<nil>
[debug]  Worker job done {/Volumes/data/photo/2008/2008 05 02/DSCN0081.JPG processed successfully <nil>}
[warn]   Error? file=/Volumes/data/photo/2008/2008 05 02/DSCN0082.JPG, error=<nil>
[warn]   Tracking file=/Volumes/data/photo/2008/2008 05 02/DSCN0082.JPG
[warn]   Tracking done file=/Volumes/data/photo/2008/2008 05 02/DSCN0082.JPG, error=<nil>
[debug]  Worker job done {/Volumes/data/photo/2008/2008 05 02/DSCN0082.JPG processed successfully <nil>}


and now it's hung
```

My patched files to achieve extra logs:
```
diff --git a/upload/enqueue.go b/upload/enqueue.go
index 8c57462..2fae085 100644
--- a/upload/enqueue.go
+++ b/upload/enqueue.go
@@ -20,13 +20,17 @@ type EnqueuedJob struct {

 func (job *EnqueuedJob) Process() error {
        // Upload the file and add it to PhotosService.
+               job.Logger.Warnf("Start file=%s", job.Path)
        _, err := job.PhotosService.AddMediaItem(job.Context, job.Path, job.albumID())
+               job.Logger.Warnf("Error? file=%s, error=%v", job.Path, err)
        if err != nil {
                return err
        }
+               job.Logger.Warnf("Tracking file=%s", job.Path)

        // Mark the file as uploaded in the FileTracker.
        err = job.FileTracker.CacheAsAlreadyUploaded(job.Path)
+               job.Logger.Warnf("Tracking done file=%s, error=%v", job.Path, err)
        if err != nil {
                job.Logger.Warnf("Tracking file as uploaded failed: file=%s, error=%v", job.Path, err)
        }
diff --git a/worker/queue.go b/worker/queue.go
index afdf4f2..6977fce 100644
--- a/worker/queue.go
+++ b/worker/queue.go
@@ -138,7 +138,7 @@ func (w *Worker) Start() {
                                        Message: "processed successfully",
                                        Err:     job.Process(),
                                }
-
+                               w.logger.Debugf("Worker job done %s", r)
                                if r.Err != nil {
                                        r.Message = "processed with errors"
                                        w.logger.Error(r.Err)
```

**Expected behavior**
Upload without problem.

**Desktop & Client versions (please complete the following information):**
 - Operating System: macOS mojave
 - Version 1.0.1 golang: 1.13.4

**Comment by rarescosma** [comment]
Same issue on Linux:

```
> uname -a
Linux *** 5.3.13-arch1-1 #1 SMP PREEMPT Sun, 24 Nov 2019 10:15:50 +0000 x86_64 GNU/Linux

> go version
go version go1.13.4 linux/amd64
```

**Comment by abdupattoh** [comment]
I am also seeing a hung process after about 40 uploads...

Linux *** 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

go version go1.13.5 linux/amd64

%vgphotos-uploader-cli version
gphotos-uploader-cli v0.0.0  (!)

**Comment by pacoorozco** [comment]
I'd like to know if each of you are having the problem after uploading the same amount of files...

**Comment by rysi3k** [comment]
@pacoorozco ha!
With 5 workers, it hangs after 55 files - 3 times in the row.
With 1 worker, it hangs after 11 files.

**Comment by pacoorozco** [comment]
Hi

I've found the problem... a patch is coming

Thanks for raising it up

**Comment by pacoorozco** [comment]
Hi
It should be fixed on v1.0.2, can you confirm it?

**Comment by abdupattoh** [comment]
Hi - 

I did a pull request that updated and rebuilt to 1.0.2, and I still see the same issue of uploading exactly 55 pictures, and then it just stops.  ;-/

I am not that experienced with git, so there is a chance I didn't get the update right, but the version does report as 1.0.2.

**Comment by rysi3k** [comment]
Hi @pacoorozco 
I have pulled yours changes, now looks good! Long process works and uploads files.
Thanks!

**Comment by abdupattoh** [comment]
Sorry to be the troublemaker, but after doing a build from a clean directory and starting with a new gphotosuploader-cli init --force I am still getting a hung process after 55 uploads.

**Comment by pacoorozco** [comment]
Hi @abdupattoh 

Have you tried to use one of the [provided binaries](https://github.com/gphotosuploader/gphotos-uploader-cli/releases/tag/v1.0.2)? 

If it still failing, please attach the outpur of `gphotos-uploader-cli version`.

**Comment by abdupattoh** [comment]
% grep -c 'Successfully'  gphotos.log.2019.12.15
575

... And it is still running.  Fixed!

The binary fixed it, so somehow the build process didn't work for me, even though it produced a 1.0.2 binary.

Thanks!
