### ISSUE TITLE
Uploading a folder structure results in creating multiple albums with the same name (concurrency issue?)

### ISSUE THREAD

**Issue by RonaldFindling** [gphotosuploader/gphotos-uploader-cli#99]
**Describe the bug**
Uploading a folder hierarchy results in having multiple folders with the same name -- a single folder on the local HD results in multiple folders in google pictures.

**To Reproduce**
1. Run `gphotos-uploader-cli` with a small folder hierachy containing folders of >= 30 pics
```
./
├── subFolder1
│   ├── subSubFolder
│   ├── subSubFolder_1_1 30 files
│   └── subSubFolder_1_2 30 files
└── subFolder2
    ├── subSubFolder_2_1 30 files
    └── subSubFolder_2_2 30 files
```
2. Check the results in `https://photos.google.com/albums`
3. There I see a folder structure like this:
```
./
├── subSubFolder
├── subSubFolder_1_1 27 files
├── subSubFolder_1_1  1 file
├── subSubFolder_1_1  2 files
├── subSubFolder_1_2 26 files
├── subSubFolder_1_2  2 files
├── subSubFolder_1_2  2 files
├── subSubFolder_2_1 26 files
├── subSubFolder_2_1  4 files
├── subSubFolder_2_2 28 files
└── subSubFolder_2_2 2 files
```

**Expected behavior**
Not having duplicated folders but just a flattened folder structure.
```
./
├── subSubFolder
├── subSubFolder_1_1 30 files
├── subSubFolder_1_2 30 files
├── subSubFolder_2_1 30 files
└── subSubFolder_2_2 30 files
```

**Screenshots**

**Desktop (please complete the following information):**
 - Ubuntu
 - 17.10

**Client (please complete the following information):**
 - gphotos-uploader-cli v0.4.2 (build: 43745dc)

**Comment by pacoorozco** [comment]
It should not happen with the last version. Albums will be created if they are going to have content on it. 

It means that, given the previous case, you should obtain:
```
./
├── subSubFolder_1_1 30 files
├── subSubFolder_1_2 30 files
├── subSubFolder_2_1 30 files
└── subSubFolder_2_2 30 files
```
It was fixed [here](https://github.com/nmrshll/gphotos-uploader-cli/commit/56d4938a2f2b91718fd196590cbe2c4161220509#diff-ffe9c370dd521ec200ef136bd4cfb81cL105). Now it's implemented here:

https://github.com/nmrshll/gphotos-uploader-cli/blob/ed356cde5cd26fe39f9e5359d9df70b10a1de1a7/upload/fileUpload.go#L72

**Can you confirm it?**

**Comment by dotanalon** [comment]
still happen on 
gphotos-uploader-cli v0.8.0 (build: e0ffe0e)
